const pageHost=document.querySelector('#pageHost'),todayPage=document.querySelector('#todayPage');
const searchInputs=document.querySelectorAll('.search input');
const escapeText=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const pageTemplates={
  library:`<header class="sub-header"><div><p class="eyebrow">KNOWLEDGE NETWORK</p><h1>知识库</h1><p>整理已收录知识，并建立你自己的知识连接</p></div><div class="library-tools"><div class="view-switch"><button class="active" data-library-view="board">主题板</button><button data-library-view="hierarchy">笔记</button><button data-library-view="graph">图谱</button></div><div class="filters"><div class="filter-control"><button data-filter-toggle="theme">全部主题</button><div class="filter-menu" data-filter-menu="theme"></div></div><div class="filter-control"><button data-filter-toggle="time">全部时间</button><div class="filter-menu" data-filter-menu="time"><button data-value="all">全部时间</button><button data-value="7">最近 7 天</button><button data-value="30">最近 30 天</button></div></div></div></div></header><section class="library-view" id="boardView"></section><section class="library-view markdown-view" id="hierarchyView" hidden></section><section class="library-view graph-view" id="graphView" hidden><div class="graph-toolbar"><span>拖动节点 · 双击查看详情 · 可手动建立连接</span><div><button data-graph-connect>建立连接</button><button data-graph-cancel hidden>取消</button></div></div><div class="graph-canvas" id="graphCanvas"><svg aria-hidden="true"></svg></div></section>`,
  uncollected:`<header class="sub-header"><div><p class="eyebrow">ARCHIVE</p><h1>未收录</h1><p>已阅但没有进入知识库的完整知识会保存在这里。</p></div></header><section class="uncollected-full-list"></section>`,
  sources:`<header class="sub-header"><div><p class="eyebrow">SOURCES</p><h1>来源记录</h1><p>查看捕捉来源与处理状态</p></div><div class="filters source-filters"><div class="filter-control"><button data-source-filter-toggle="type">全部类型</button><div class="filter-menu" data-source-filter-menu="type"><button data-value="all">全部类型</button><button data-value="link">链接</button><button data-value="text">文字</button><button data-value="image">截图</button></div></div><div class="filter-control"><button data-source-filter-toggle="status">全部状态</button><div class="filter-menu" data-source-filter-menu="status"><button data-value="all">全部状态</button><button data-value="complete">已生成</button><button data-value="working">待生成</button><button data-value="pending">待补充</button><button data-value="failed">解析失败</button></div></div></div></header><section class="source-table"><div class="source-head"><span>来源</span><span>捕捉时间</span><span>状态</span><span>知识</span></div></section>`,
  settings:`<header class="sub-header"><div><p class="eyebrow">PREFERENCES</p><h1>设置</h1><p>管理知识生成、提醒和本地数据</p></div></header><section class="settings-group"><h2>今日知识</h2><label><span><strong>生成时间</strong><small>每天在你方便阅读的时间整理知识</small></span><input type="time" value="22:00"></label><label><span><strong>阅读提醒</strong><small>知识单准备好后发送通知</small></span><input class="switch" type="checkbox" checked></label><div class="api-actions"><button data-notification-access>检查通知权限</button><span data-notification-status>正在检查…</span></div></section><section class="settings-group api-settings"><h2>AI 后端</h2><label><span><strong>服务地址</strong><small>必须使用你部署的 HTTPS 地址</small></span><input id="apiBaseInput" type="url" placeholder="https://api.example.com"></label><div class="api-actions"><button id="saveApiBase">保存地址</button><button id="testApiBase">测试连接</button><span id="apiStatus">未配置</span></div></section><section class="settings-group danger-zone"><h2>危险操作</h2><button class="setting-row" data-clear-local><span><strong>清除本地数据</strong><small>删除知识库、未收录和阅读状态</small></span><b>清除</b></button></section><p class="version">PinMind Beta · v0.7.0</p>`,
  search:query=>`<header class="sub-header"><div><p class="eyebrow">SEARCH</p><h1>“${escapeText(query)}”的搜索结果</h1><p data-search-count>正在搜索真实数据…</p></div></header><div class="search-tabs"><button class="active" data-search-scope="library">知识库</button><button data-search-scope="uncollected">未收录</button><button data-search-scope="sources">来源记录</button></div><section class="result-list"></section>`
};

let liveSources=[],graphStart=null,graphConnecting=false;
const readJson=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const writeJson=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const itemKey=item=>item.id||item.headline;
function sourceView(item){
  const type=item.url?'link':item.input_type==='screenshot'?'image':'text',labels={link:['↗','网页链接'],image:['▧','截图'],text:['文','选中文字']};
  const raw=item.parse_status==='failed'?'failed':item.status==='needs_input'?'pending':item.status==='generated'?'complete':'working';
  const statuses={complete:['ok','● 已生成'],working:['working','● 待生成'],pending:['warn','● 待补充'],failed:['failed','● 解析失败']};
  return {type,label:labels[type],status:raw,statusLabel:statuses[raw]};
}
function sourceTime(value){const date=new Date(value);if(Number.isNaN(date.getTime()))return '时间未知';return date.toDateString()===new Date().toDateString()?'今天 '+date.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}):date.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'});}
async function loadLiveSources(){
  const table=pageHost.querySelector('.source-table');if(!table)return;table.querySelectorAll('.source-row,.source-state').forEach(row=>row.remove());table.insertAdjacentHTML('beforeend','<div class="source-state">正在同步来源记录…</div>');
  try{const data=await PinMindAPI.sources();liveSources=data.sources||[];table.querySelector('.source-state')?.remove();
    if(!liveSources.length){table.insertAdjacentHTML('beforeend','<div class="source-state">暂无来源。分享链接、文字或截图到 PinMind 后会显示在这里。</div>');return;}
    liveSources.forEach(item=>{const view=sourceView(item),count=(item.generated_knowledge_ids||[]).length;table.insertAdjacentHTML('beforeend',`<button class="source-row" data-source-id="${escapeText(item.id)}" data-source-type="${view.type}" data-source-status="${view.status}" data-source-url="${escapeText(item.url||'')}"><i class="source-icon ${view.type}-icon">${view.label[0]}</i><span><strong>${escapeText(item.title||'未命名来源')}</strong><small>${view.label[1]}</small></span><time>${sourceTime(item.captured_at)}</time><em class="${view.statusLabel[0]}">${view.statusLabel[1]}</em><b>${count?count+' 条':'—'}</b></button>`)});applySourceFilters();
  }catch(error){table.querySelector('.source-state')?.remove();table.insertAdjacentHTML('beforeend',`<div class="source-state source-error">来源同步失败：${escapeText(error.message)} <button data-retry-sources>重新加载</button></div>`);}
}
function emptyBlock(title,text){return `<section class="empty-state"><h2>${escapeText(title)}</h2><p>${escapeText(text)}</p></section>`;}
function libraryItems(){return PinMindState.library();}
function renderLibrary(){
  const items=libraryItems(),board=pageHost.querySelector('#boardView'),note=pageHost.querySelector('#hierarchyView'),canvas=pageHost.querySelector('#graphCanvas');if(!board)return;
  board.innerHTML='<div class="board-note">拖动卡片调整顺序 · 点击卡片查看详情 · 删除不会影响原始来源</div>';
  const grouped=new Map();items.forEach(item=>{const topic=item.topic||'未分类';if(!grouped.has(topic))grouped.set(topic,[]);grouped.get(topic).push(item)});
  grouped.forEach((entries,topic)=>{const cluster=document.createElement('section');cluster.className='cluster dynamic-cluster';cluster.dataset.theme=topic;cluster.innerHTML=`<div class="cluster-title"><span>${escapeText(topic)}</span><small>${entries.length} 条知识</small></div><div class="draggable-board"></div>`;entries.forEach(item=>cluster.querySelector('.draggable-board').insertAdjacentHTML('beforeend',`<article class="knowledge-module" draggable="true" data-key="${escapeText(itemKey(item))}" data-theme="${escapeText(topic)}"><button class="module-delete" aria-label="删除">×</button><span>${escapeText(item.type||'知识')}</span><h3>${escapeText(item.headline)}</h3><small>${escapeText(item.digestDate||'已收录')}</small></article>`));board.appendChild(cluster)});
  if(!items.length)board.insertAdjacentHTML('beforeend',emptyBlock('知识库还是空的','在今日知识中点击“加入知识库”后，内容会出现在这里。'));
  renderMarkdown(note,items);renderGraph(canvas,items);refreshThemeOptions(grouped);
}
function markdownFor(items){return items.map(item=>{const sections=item.sections||[],lines=[`# ${item.headline}`];sections.forEach(section=>{const level=Math.max(0,Math.min(3,Number(section.level)||0));if(level===0){lines.push('',`> ${section.content||section.title}`);(section.items||[]).forEach(point=>lines.push(`> - ${point}`));return;}lines.push('',`${'#'.repeat(level+1)} ${section.title}`,'',section.content||'');(section.items||[]).forEach(point=>lines.push(`- ${point}`));});lines.push('','## 原始来源','',`- ${item.source||'原始来源'}${item.url&&item.url!=='#'?'：'+item.url:''}`);return lines.join('\n')}).join('\n\n---\n\n');}
function noteAnchor(index,sectionIndex){return `note-${index}${sectionIndex===undefined?'':'-'+sectionIndex}`;}
function renderMarkdown(view,items){
  if(!view)return;if(!items.length){view.innerHTML='<div class="board-note">笔记会根据已收录知识自动生成</div>'+emptyBlock('暂无可复制的笔记','先从今日知识收录内容。');return;}
  view.innerHTML='<div class="board-note">目录与主题会根据已收录知识实时更新</div><div class="notes-layout"><aside class="note-toc"><strong>目录</strong><nav></nav></aside><article class="markdown-document"><header><span>PinMind 知识笔记</span><button data-copy-markdown>复制 Markdown</button></header><div class="markdown-output"></div></article></div>';
  const toc=view.querySelector('.note-toc nav'),output=view.querySelector('.markdown-output');
  items.forEach((item,index)=>{
    const theme=item.topic||'未分类',sections=item.sections||[],anchor=noteAnchor(index);
    const tocItem=document.createElement('div');tocItem.className='toc-item';tocItem.dataset.theme=theme;tocItem.dataset.key=itemKey(item);tocItem.innerHTML=`<button data-note-target="${anchor}"><span>${String(index+1).padStart(2,'0')}</span>${escapeText(item.headline)}</button><div>${sections.filter(section=>Number(section.level)>0).map((section,sectionIndex)=>`<button class="toc-level-${Math.min(3,Number(section.level)||1)}" data-note-target="${noteAnchor(index,sectionIndex)}">${escapeText(section.title)}</button>`).join('')}</div>`;toc.appendChild(tocItem);
    const note=document.createElement('section');note.className='markdown-note';note.id=anchor;note.dataset.theme=theme;note.dataset.key=itemKey(item);note.dataset.date=item.digestDate||'';
    let body=`<div class="note-meta"><span>${escapeText(theme)}</span><time>${escapeText(item.digestDate||'')}</time></div><h1>${escapeText(item.headline)}</h1>`;
    let outlineIndex=0;sections.forEach(section=>{const level=Math.max(0,Math.min(3,Number(section.level)||0));if(level===0){body+=`<blockquote>${escapeText(section.content||section.title)}${(section.items||[]).length?`<ul>${section.items.map(point=>`<li>${escapeText(point)}</li>`).join('')}</ul>`:''}</blockquote>`;return;}const id=noteAnchor(index,outlineIndex++),tag=level===1?'h2':level===2?'h3':'h4';body+=`<${tag} id="${id}">${escapeText(section.title)}</${tag}>${section.content?`<p>${escapeText(section.content)}</p>`:''}${(section.items||[]).length?`<ul>${section.items.map(point=>`<li>${escapeText(point)}</li>`).join('')}</ul>`:''}`});
    if(item.url&&item.url!=='#')body+=`<a href="${escapeText(item.url)}">查看原始来源 ↗</a>`;note.innerHTML=body;output.appendChild(note);
  });view.dataset.markdown=markdownFor(items);
}
function refreshThemeOptions(grouped){
  const menu=pageHost.querySelector('[data-filter-menu="theme"]'),trigger=pageHost.querySelector('[data-filter-toggle="theme"]');if(!menu)return;
  const topics=[...grouped.keys()].sort((a,b)=>a.localeCompare(b,'zh-CN'));menu.innerHTML='<button data-value="all">全部主题</button>'+topics.map(topic=>`<button data-value="${escapeText(topic)}">${escapeText(topic)}（${grouped.get(topic).length}）</button>`).join('');
  const current=pageHost.dataset.libraryTheme||'all';if(current!=='all'&&!grouped.has(current)){pageHost.dataset.libraryTheme='all';if(trigger)trigger.textContent='全部主题';}
}
function graphEdges(){return readJson('pinmind.graphEdges',[])}
function graphLabel(item){const explicit=(item.graphLabel||'').trim();if(explicit)return explicit.slice(0,10);const topic=(item.topic||'').trim();if(topic&&topic!=='未分类')return topic.slice(0,10);const tag=(item.tags||[]).find(value=>String(value).trim());return tag?String(tag).trim().slice(0,10):'知识';}
function renderGraph(canvas,items){if(!canvas)return;canvas.querySelectorAll('.graph-node,.graph-empty').forEach(node=>node.remove());const deleted=new Set(readJson('pinmind.graphDeleted',[])),positions=readJson('pinmind.graphPositions',{});items.filter(item=>!deleted.has(itemKey(item))).forEach((item,index)=>{const key=itemKey(item),position=positions[key]||{left:18+(index%4)*22,top:24+Math.floor(index/4)*24};const node=document.createElement('div');node.className='graph-node leaf';node.dataset.node=key;node.dataset.theme=item.topic||'未分类';node.style.left=position.left+'%';node.style.top=position.top+'%';node.tabIndex=0;node.innerHTML=`<span>${escapeText(graphLabel(item))}</span><button class="graph-node-delete" aria-label="删除节点">×</button>`;canvas.appendChild(node)});if(!canvas.querySelector('.graph-node'))canvas.insertAdjacentHTML('beforeend','<div class="graph-empty">暂无节点。收录知识后可在这里手动建立连接。</div>');updateGraphEdges();}
function updateGraphEdges(){const canvas=pageHost.querySelector('#graphCanvas');if(!canvas||canvas.closest('[hidden]'))return;const svg=canvas.querySelector('svg'),width=canvas.clientWidth,height=canvas.clientHeight;if(!width||!height)return;svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.innerHTML='';graphEdges().forEach(([from,to])=>{const a=[...canvas.querySelectorAll('.graph-node')].find(node=>node.dataset.node===from),b=[...canvas.querySelectorAll('.graph-node')].find(node=>node.dataset.node===to);if(!a||!b||a.hidden||b.hidden)return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',a.offsetLeft+a.offsetWidth/2);line.setAttribute('y1',a.offsetTop+a.offsetHeight/2);line.setAttribute('x2',b.offsetLeft+b.offsetWidth/2);line.setAttribute('y2',b.offsetTop+b.offsetHeight/2);svg.appendChild(line)});}
function cancelConnection(){graphConnecting=false;graphStart=null;pageHost.querySelectorAll('.graph-node').forEach(node=>node.classList.remove('connect-start'));const connect=pageHost.querySelector('[data-graph-connect]'),cancel=pageHost.querySelector('[data-graph-cancel]');if(connect)connect.textContent='建立连接';if(cancel)cancel.hidden=true;}
function graphNodeTap(node){if(!graphConnecting)return;const key=node.dataset.node;if(!graphStart){graphStart=key;node.classList.add('connect-start');pageHost.querySelector('[data-graph-connect]').textContent='请选择第二个节点';return;}if(key!==graphStart){const edges=graphEdges(),exists=edges.some(([a,b])=>(a===graphStart&&b===key)||(a===key&&b===graphStart));if(!exists){edges.push([graphStart,key]);writeJson('pinmind.graphEdges',edges)}}cancelConnection();updateGraphEdges();}
function renderUncollected(){const list=pageHost.querySelector('.uncollected-full-list');if(!list)return;const items=PinMindState.uncollected();list.innerHTML=items.length?'':emptyBlock('暂无未收录知识','点击“已阅”时未加入知识库的内容会出现在这里。');items.forEach(item=>{const card=document.createElement('article');card.className='uncollected-card';card._item=item;card.innerHTML=`<div class="uncollected-meta"><span>${escapeText(item.topic||'未收录')}</span><time>${escapeText(item.digestDate||'')}</time></div><h2>${escapeText(item.headline)}</h2><p>${escapeText(item.paragraphs?.[0]||'')}</p><div class="row-actions"><button class="collect-small">＋ 加入知识库</button><button class="danger">删除</button></div>`;list.appendChild(card)});}
function openPage(page,query=''){
  document.querySelectorAll('.nav-item[data-page]').forEach(item=>item.classList.toggle('active',item.dataset.page===page));
  todayPage.hidden=page!=='today';pageHost.hidden=page==='today';
  if(page==='today')return;
  pageHost.innerHTML=page==='search'?pageTemplates.search(query):pageTemplates[page];
  if(page==='library')renderLibrary();
  if(page==='uncollected')renderUncollected();
  if(page==='sources')loadLiveSources();
  if(page==='search')runSearch(query,'library');
  if(page==='settings'){pageHost.querySelector('input[type=time]').value=localStorage.getItem('pinmind.dailyTime')||'22:00';pageHost.querySelector('.switch').checked=localStorage.getItem('pinmind.notifications')!=='0';pageHost.querySelector('#apiBaseInput').value=localStorage.getItem('pinmind.apiBase')||'';refreshNotificationStatus();}
  document.querySelector('main').scrollTo({top:0,behavior:'smooth'});
}
function resultItems(scope){if(scope==='library')return libraryItems();if(scope==='uncollected')return PinMindState.uncollected();return liveSources.map(item=>({headline:item.title,paragraphs:[item.content||''],topic:'来源记录',source:item.url||item.input_type}));}
async function runSearch(query,scope){if(scope==='sources'&&!liveSources.length){try{liveSources=(await PinMindAPI.sources()).sources||[]}catch{liveSources=[]}}const term=query.trim().toLowerCase(),results=resultItems(scope).filter(item=>JSON.stringify(item).toLowerCase().includes(term)),list=pageHost.querySelector('.result-list');pageHost.querySelector('[data-search-count]').textContent=`找到 ${results.length} 条真实内容`;list.innerHTML=results.length?'':emptyBlock('没有搜索结果','换一个关键词试试。');results.forEach(item=>list.insertAdjacentHTML('beforeend',`<article><span>${escapeText(item.topic||scope)}</span><h2>${escapeText(item.headline||'未命名')}</h2><p>${escapeText(item.paragraphs?.[0]||'')}</p><small>${escapeText(item.source||'')}</small></article>`));}

const historyData=new Map();
async function loadHistory(){
  historyData.clear();const section=document.querySelector('.history');section.querySelectorAll('.history-item,.history-state').forEach(item=>item.remove());
  try{const [data,sourceData]=await Promise.all([PinMindAPI.history(),PinMindAPI.sources().catch(()=>({sources:[]}))]);(data.digests||[]).forEach(digest=>{const items=window.mapKnowledgeItems?.(digest.knowledge_items,sourceData.sources||[])||[];if(!items.length||PinMindState.isRead(digest.digest_date,items))return;historyData.set(digest.digest_date,items);const date=new Date(digest.digest_date+'T00:00:00+08:00'),button=document.createElement('button');button.className='history-item';button.dataset.digestDate=digest.digest_date;button.innerHTML=`<span class="history-dot"></span><span><time>${date.getMonth()+1}月${date.getDate()}日</time><strong>${escapeText(items[0].headline)}</strong><em>${items.length} 条知识</em></span>`;section.appendChild(button)});if(!section.querySelector('.history-item'))section.insertAdjacentHTML('beforeend','<small class="history-state">暂无</small>');}catch(error){section.insertAdjacentHTML('beforeend','<small class="history-state">历史知识暂时无法加载</small>');}
}
document.querySelector('.history').addEventListener('click',event=>{const button=event.target.closest('.history-item');if(!button)return;const date=button.dataset.digestDate,items=historyData.get(date)||[];window.viewingToday=false;openPage('today');document.querySelector('#todayPage h1').textContent='历史知识';const display=new Date(date+'T00:00:00+08:00');document.querySelector('.date').textContent=`${display.getMonth()+1}月${display.getDate()}日`;window.renderKnowledgeItems(items,date);window.applyReadState?.();document.querySelector('[data-page="today"]').classList.remove('active');});
window.addEventListener('pinmind:read-state-changed',loadHistory);document.querySelectorAll('.nav-item[data-page]').forEach(item=>item.addEventListener('click',()=>{if(item.dataset.page==='today'){window.viewingToday=true;document.querySelector('#todayPage h1').textContent='今日知识';window.loadLiveDigest?.()}openPage(item.dataset.page);document.querySelector('#sidebar').classList.remove('open');document.querySelector('#scrim').classList.remove('open')}));
searchInputs.forEach(input=>input.addEventListener('keydown',event=>{if(event.key==='Enter'&&input.value.trim()){openPage('search',input.value.trim());document.querySelector('#mobileSearch')?.classList.remove('open')}}));
document.querySelector('#viewLibraryButton').addEventListener('click',event=>{event.preventDefault();openPage(event.currentTarget.dataset.page);});
document.querySelector('#mobileSearchButton').addEventListener('click',()=>{const search=document.querySelector('#mobileSearch');search.classList.add('open');search.setAttribute('aria-hidden','false');search.querySelector('input').focus()});
document.querySelector('#closeMobileSearch').addEventListener('click',()=>{const search=document.querySelector('#mobileSearch');search.classList.remove('open');search.setAttribute('aria-hidden','true')});
document.querySelector('#menuButton').addEventListener('click',()=>{document.querySelector('#sidebar').classList.add('open');document.querySelector('#scrim').classList.add('open')});
document.querySelector('#scrim').addEventListener('click',()=>{document.querySelector('#sidebar').classList.remove('open');document.querySelector('#drawer').classList.remove('open');document.querySelector('#scrim').classList.remove('open')});
pageHost.addEventListener('click',async event=>{
  const view=event.target.closest('[data-library-view]');if(view){pageHost.querySelectorAll('[data-library-view]').forEach(button=>button.classList.toggle('active',button===view));['board','hierarchy','graph'].forEach(name=>pageHost.querySelector('#'+name+'View').hidden=view.dataset.libraryView!==name);if(view.dataset.libraryView==='graph')requestAnimationFrame(updateGraphEdges);return;}
  if(event.target.closest('[data-graph-connect]')){graphConnecting=true;pageHost.querySelector('[data-graph-cancel]').hidden=false;event.target.textContent='请选择第一个节点';return;}if(event.target.closest('[data-graph-cancel]')){cancelConnection();return;}
  const graphDelete=event.target.closest('.graph-node-delete');if(graphDelete){event.stopPropagation();const key=graphDelete.closest('.graph-node').dataset.node,deleted=new Set(readJson('pinmind.graphDeleted',[]));deleted.add(key);writeJson('pinmind.graphDeleted',[...deleted]);writeJson('pinmind.graphEdges',graphEdges().filter(edge=>!edge.includes(key)));renderGraph(pageHost.querySelector('#graphCanvas'),libraryItems());return;}
  const graphNode=event.target.closest('.graph-node');if(graphNode){graphNodeTap(graphNode);return;}
  const remove=event.target.closest('.module-delete');if(remove){event.stopPropagation();const card=remove.closest('.knowledge-module'),item=libraryItems().find(entry=>itemKey(entry)===card.dataset.key);if(item&&PinMindState.isCollected(item))PinMindState.toggleCollected(item,item.digestDate);renderLibrary();return;}
  const module=event.target.closest('.knowledge-module');if(module){showKnowledgeDetail(libraryItems().find(item=>itemKey(item)===module.dataset.key));return;}
  const copy=event.target.closest('[data-copy-markdown]');if(copy){const text=pageHost.querySelector('#hierarchyView').dataset.markdown||'';try{if(window.PinMindNative?.copyText)window.PinMindNative.copyText(text);else await navigator.clipboard.writeText(text);copy.textContent='✓ 已复制';setTimeout(()=>copy.textContent='复制 Markdown',1200)}catch{copy.textContent='复制失败'}return;}
  const collect=event.target.closest('.collect-small');if(collect){const item=collect.closest('.uncollected-card')._item;PinMindState.toggleCollected(item,item.digestDate);renderUncollected();return;}
  const danger=event.target.closest('.uncollected-card .danger');if(danger){if(confirm('删除这条未收录知识？删除后无法恢复。')){PinMindState.deleteUncollected(danger.closest('.uncollected-card')._item);renderUncollected()}return;}
  const source=event.target.closest('.source-row');if(source){const item=liveSources.find(entry=>entry.id===source.dataset.sourceId);if(source.dataset.sourceUrl){window.PinMindNative?.openUrl?.(source.dataset.sourceUrl);if(!window.PinMindNative)window.open(source.dataset.sourceUrl,'_blank');}else showSourceDetail(item);return;}
  const retry=event.target.closest('[data-retry-sources]');if(retry){loadLiveSources();return;}
  const tab=event.target.closest('[data-search-scope]');if(tab){pageHost.querySelectorAll('[data-search-scope]').forEach(button=>button.classList.toggle('active',button===tab));runSearch(pageHost.querySelector('.sub-header h1').textContent.match(/“(.+)”/)?.[1]||'',tab.dataset.searchScope);return;}
  const filter=event.target.closest('[data-filter-toggle],[data-source-filter-toggle]');if(filter){event.stopPropagation();const kind=filter.dataset.filterToggle||filter.dataset.sourceFilterToggle,menu=pageHost.querySelector(`[data-filter-menu="${kind}"],[data-source-filter-menu="${kind}"]`);menu.classList.toggle('open');return;}
  const option=event.target.closest('.filter-menu [data-value]');if(option){applyFilterOption(option);return;}
  if(event.target.closest('#saveApiBase')){const value=pageHost.querySelector('#apiBaseInput').value.trim().replace(/\/$/,'');localStorage.setItem('pinmind.apiBase',value);window.PinMindNative?.setApiBase?.(value);pageHost.querySelector('#apiStatus').textContent='已保存';return;}
  if(event.target.closest('#testApiBase')){const status=pageHost.querySelector('#apiStatus');status.textContent='连接中…';try{const health=await PinMindAPI.health();status.textContent=health.ai_configured?'连接成功 · AI 已配置':'连接成功 · 未配置 Key'}catch(error){status.textContent='连接失败：'+error.message}return;}
  if(event.target.closest('[data-clear-local]')&&confirm('清除 PinMind 本地知识和阅读状态？')){['pinmind.collected','pinmind.libraryItems','pinmind.uncollected','pinmind.readDates','pinmind.graphEdges','pinmind.graphDeleted','pinmind.graphPositions'].forEach(key=>localStorage.removeItem(key));openPage('settings');}
});
function applyLibraryFilters(){const theme=pageHost.dataset.libraryTheme||'all',days=Number(pageHost.dataset.libraryDays||0),now=Date.now(),items=libraryItems();pageHost.querySelectorAll('.knowledge-module,.markdown-note').forEach(card=>{const item=items.find(entry=>itemKey(entry)===card.dataset.key),date=new Date(item?.digestDate),themeMatch=theme==='all'||item?.topic===theme,timeMatch=!days||(date.getTime()&&now-date.getTime()<=days*86400000);card.hidden=!themeMatch||!timeMatch});pageHost.querySelectorAll('.cluster').forEach(cluster=>cluster.hidden=theme!=='all'&&cluster.dataset.theme!==theme);pageHost.querySelectorAll('.graph-node').forEach(node=>node.hidden=theme!=='all'&&node.dataset.theme!==theme);pageHost.querySelectorAll('.toc-item').forEach(entry=>{const note=pageHost.querySelector(`.markdown-note[data-key="${CSS.escape(entry.dataset.key)}"]`);entry.hidden=!note||note.hidden});updateGraphEdges();}
function applyFilterOption(option){const menu=option.closest('.filter-menu'),kind=menu.dataset.filterMenu||menu.dataset.sourceFilterMenu,trigger=pageHost.querySelector(`[data-filter-toggle="${kind}"],[data-source-filter-toggle="${kind}"]`);trigger.textContent=option.textContent;menu.classList.remove('open');if(menu.dataset.sourceFilterMenu){pageHost.dataset[kind==='type'?'sourceType':'sourceStatus']=option.dataset.value;applySourceFilters();return;}if(kind==='theme')pageHost.dataset.libraryTheme=option.dataset.value;if(kind==='time')pageHost.dataset.libraryDays=option.dataset.value==='all'?'0':option.dataset.value;applyLibraryFilters();}
function applySourceFilters(){const type=pageHost.dataset.sourceType||'all',status=pageHost.dataset.sourceStatus||'all';pageHost.querySelectorAll('.source-row').forEach(row=>row.hidden=(type!=='all'&&row.dataset.sourceType!==type)||(status!=='all'&&row.dataset.sourceStatus!==status));}
let dragged=null;pageHost.addEventListener('dragstart',event=>{dragged=event.target.closest('.knowledge-module')});pageHost.addEventListener('dragover',event=>{const board=event.target.closest('.draggable-board');if(!board||!dragged)return;event.preventDefault();const target=event.target.closest('.knowledge-module');if(target&&target!==dragged)board.insertBefore(dragged,target);else if(!target)board.appendChild(dragged)});pageHost.addEventListener('dragend',()=>dragged=null);
pageHost.addEventListener('pointerdown',event=>{const node=event.target.closest('.graph-node');if(!node||event.target.closest('.graph-node-delete')||graphConnecting)return;node.setPointerCapture(event.pointerId);const canvas=node.parentElement,rect=canvas.getBoundingClientRect();const move=e=>{node.style.left=Math.max(5,Math.min(95,(e.clientX-rect.left)/rect.width*100))+'%';node.style.top=Math.max(6,Math.min(94,(e.clientY-rect.top)/rect.height*100))+'%';updateGraphEdges()};const up=()=>{node.removeEventListener('pointermove',move);const positions=readJson('pinmind.graphPositions',{});positions[node.dataset.node]={left:parseFloat(node.style.left),top:parseFloat(node.style.top)};writeJson('pinmind.graphPositions',positions)};node.addEventListener('pointermove',move);node.addEventListener('pointerup',up,{once:true})});
pageHost.addEventListener('dblclick',event=>{const node=event.target.closest('.graph-node');if(node)showKnowledgeDetail(libraryItems().find(item=>itemKey(item)===node.dataset.node));});
function showSourceDetail(item){if(!item)return;const drawer=document.querySelector('#drawer'),view=sourceView(item);drawer.querySelector('header p').textContent='来源详情';drawer.querySelector('header h2').textContent=item.title||'未命名来源';drawer.querySelector('.drawer-body').innerHTML=`<span class="topic-tag mint">${view.statusLabel[1].replace('● ','')}</span><p class="drawer-lead">${escapeText(item.content||'没有可预览的文字内容')}</p><div class="source-panel"><span>内容完整度：${escapeText(item.completeness||'未知')} · 已生成 ${(item.generated_knowledge_ids||[]).length} 条知识</span></div>`;drawer.classList.add('open');document.querySelector('#scrim').classList.add('open');drawer.setAttribute('aria-hidden','false');}function showKnowledgeDetail(item){if(!item)return;const drawer=document.querySelector('#drawer');drawer.querySelector('header p').textContent='知识详情';drawer.querySelector('header h2').textContent=item.headline;drawer.querySelector('.drawer-body').innerHTML=`<span class="topic-tag mint">${escapeText(item.topic||'未分类')}</span>${(item.paragraphs||[]).map(text=>`<p class="drawer-lead">${escapeText(text)}</p>`).join('')}<div class="source-panel"><span>由 PinMind AI 基于原始内容整理，请结合来源判断。</span>${item.url&&item.url!=='#'?`<a href="${escapeText(item.url)}">查看原始来源 ↗</a>`:''}</div>`;drawer.classList.add('open');document.querySelector('#scrim').classList.add('open');drawer.setAttribute('aria-hidden','false');}
document.querySelector('#closeDrawer').addEventListener('click',()=>{document.querySelector('#drawer').classList.remove('open');document.querySelector('#scrim').classList.remove('open')});
function refreshNotificationStatus(){const status=pageHost.querySelector('[data-notification-status]');if(!status)return;try{status.textContent=window.PinMindNative?.getNotificationStatus?.()||'仅安卓端支持系统通知'}catch{status.textContent='无法读取通知状态'}}
pageHost.addEventListener('change',event=>{if(event.target.matches('input[type=time]')){localStorage.setItem('pinmind.dailyTime',event.target.value);window.PinMindNative?.setDailyTime?.(event.target.value);updateDailySchedule()}if(event.target.matches('.switch')){localStorage.setItem('pinmind.notifications',event.target.checked?'1':'0');window.PinMindNative?.setNotificationsEnabled?.(event.target.checked);setTimeout(refreshNotificationStatus,400)}});
pageHost.addEventListener('click',event=>{const target=event.target.closest('[data-note-target]');if(target){const note=document.getElementById(target.dataset.noteTarget);if(note)note.scrollIntoView({behavior:'smooth',block:'start'});return;}if(event.target.closest('[data-notification-access]')){const status=pageHost.querySelector('[data-notification-status]');if(status)status.textContent='正在检查系统权限…';if(window.PinMindNative?.requestNotificationAccess)window.PinMindNative.requestNotificationAccess();else if(status)status.textContent='请在安卓 App 中检查';setTimeout(refreshNotificationStatus,1200)}});
document.addEventListener('click',event=>{if(!event.target.closest('.filter-control'))document.querySelectorAll('.filter-menu').forEach(menu=>menu.classList.remove('open'))});window.addEventListener('resize',updateGraphEdges);window.addEventListener('pinmind:sources-updated',loadLiveSources);

loadHistory();
